# Generated by Django 3.1.5 on 2022-02-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20220225_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(blank=True, default='d', max_length=100),
            preserve_default=False,
        ),
    ]
