# Generated by Django 4.0.3 on 2022-03-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_sender_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.TextField(default='afaris', max_length=100),
            preserve_default=False,
        ),
    ]
